/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Pro-Density Admin tokens (from DESIGN.md)
        'on-surface': '#191c1e',
        'surface-tint': '#004ced',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#001452',
        'surface-variant': '#e0e3e5',
        'on-tertiary-container': '#d6e6ff',
        primary: '#003ec7',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#bec6e0',
        tertiary: '#3f4f65',
        'surface-container': '#eceef0',
        'inverse-on-surface': '#eff1f3',
        'on-secondary-fixed': '#131b2e',
        'error-container': '#ffdad6',
        'inverse-primary': '#b7c4ff',
        'tertiary-container': '#57677e',
        'primary-container': '#0052ff',
        'tertiary-fixed': '#d3e4fe',
        'outline-variant': '#c3c5d9',
        secondary: '#565e74',
        'on-secondary-container': '#5c647a',
        surface: '#f7f9fb',
        'inverse-surface': '#2d3133',
        'surface-bright': '#f7f9fb',
        'primary-fixed': '#dde1ff',
        'on-tertiary-fixed': '#0b1c30',
        outline: '#737688',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'secondary-fixed': '#dae2fd',
        'on-primary-container': '#dfe3ff',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#38485d',
        'on-surface-variant': '#434656',
        'on-background': '#191c1e',
        'primary-fixed-dim': '#b7c4ff',
        'on-secondary-fixed-variant': '#3f465c',
        background: '#f7f9fb',
        'secondary-container': '#dae2fd',
        'surface-container-highest': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'surface-dim': '#d8dadc',
        'tertiary-fixed-dim': '#b7c8e1',
        'surface-container-high': '#e6e8ea',
        'on-primary-fixed-variant': '#0038b6',
        // Semantic aliases used across the app
        'sidebar': '#0f172a',
        'sidebar-hover': '#1e293b',
        'sidebar-active': '#1d4ed8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '24px',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'mono-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500', letterSpacing: '0.02em' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        popover: '0px 4px 6px -1px rgba(0, 0, 0, 0.1)',
        card: '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
      },
      keyframes: {
        barGrow: { from: { transform: 'scaleY(0)' }, to: { transform: 'scaleY(1)' } },
        barGrowH: { from: { transform: 'scaleX(0)' }, to: { transform: 'scaleX(1)' } },
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideIn: { from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
      },
      animation: {
        'bar-grow': 'barGrow 1s ease-out forwards',
        'bar-grow-h': 'barGrowH 1s ease-out forwards',
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-in': 'slideIn 0.25s ease-out',
      },
    },
  },
  plugins: [],
};
